# Generated by Django 3.2.7 on 2021-09-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_userreg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReg',
            new_name='Cand',
        ),
    ]
